base = {'Acrobatics': 'DEX',
 'Arcana': 'INT',
 'Athletics': 'STR',
 'Bluff': 'CHA',
 'Diplomacy': 'CHA',
 'Engineering': 'INT',
 'Geography': 'INT',
 'History': 'INT',
 'Intimidate': 'CHA',
 'Larceny': 'DEX',
 'Medicine': 'INT',
 'Nature': 'INT',
 'Perception': 'WIS',
 'Ride': 'DEX',
 'Stealth': 'DEX',
 'Vigor': 'CON'}